//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitcherPanelCSharp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RouletteTableEntities1 : DbContext
    {
        public RouletteTableEntities1()
            : base("name=RouletteTableEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<colornumber> colornumbers { get; set; }
        public virtual DbSet<Errorlogtable> Errorlogtables { get; set; }
        public virtual DbSet<WiningNumbersTbl> WiningNumbersTbls { get; set; }
    }
}
