//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitcherPanelCSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WiningNumbersTbl
    {
        public int Id { get; set; }
        public string WinningNumbers { get; set; }
        public Nullable<System.DateTime> SpinDate { get; set; }
        public Nullable<int> Addbit { get; set; }
    }
}
